using System.Text;
using Abp.Dependency;
using Abp.Extensions;
using Abp.Web.Api.Modeling;
using Abp.Web.Api.ProxyScripting.Generators;
using NJsonSchema.Generation;
using System.Threading.Tasks;
using System.Linq;
using Abp;
using System;

namespace Satrabel.OpenApp.ProxyScripting
{

    class JsonSchemaProxyScriptGenerator : IProxyScriptGenerator, ITransientDependency
    {
        /// <summary>
        /// "jquery".
        /// </summary>
        public const string Name = "json";

        private JsonSchemaGenerator generator;

        public JsonSchemaProxyScriptGenerator()
        {
            var settings = new JsonSchemaGeneratorSettings();
            settings.FlattenInheritanceHierarchy = true;
            settings.DefaultPropertyNameHandling = NJsonSchema.PropertyNameHandling.CamelCase;
            settings.DefaultReferenceTypeNullHandling = NJsonSchema.ReferenceTypeNullHandling.NotNull;
            settings.AllowReferencesWithProperties = true;
            settings.SchemaType = NJsonSchema.SchemaType.Swagger2;
            generator = new JsonSchemaGenerator(settings);
        }


        public string CreateScript(ApplicationApiDescriptionModel model)
        {
            var script = new StringBuilder();
            script.AppendLine("/* This file is automatically generated by OpenApp. */");
            script.AppendLine();
            script.AppendLine("var abp = abp || {};");
            script.AppendLine("abp.schemas = abp.schemas || {};");
            foreach (var module in model.Modules.Values)
            {
                script.AppendLine();
                AddModuleScript(script, module);
            }
            return script.ToString();
        }

        private void AddModuleScript(StringBuilder script, ModuleApiDescriptionModel module)
        {
            script.AppendLine($"// module '{module.Name.ToCamelCase()}'");
            script.AppendLine("(function(){");
            script.AppendLine();
            script.AppendLine($"abp.schemas.{module.Name.ToCamelCase()} = abp.schemas.{module.Name.ToCamelCase()} || {{}};");
            foreach (var controller in module.Controllers.Values)
            {
                script.AppendLine();
                AddControllerScript(script, module, controller);
            }
            script.AppendLine();
            script.AppendLine("})();");
        }
        private void AddControllerScript(StringBuilder script, ModuleApiDescriptionModel module, ControllerApiDescriptionModel controller)
        {
            script.AppendLine($"// controller '{controller.Name.ToCamelCase()}'");
            script.AppendLine($"abp.schemas.{module.Name.ToCamelCase()}.{controller.Name.ToCamelCase()} = abp.schemas.{module.Name.ToCamelCase()}.{controller.Name.ToCamelCase()} || {{}};");
            /*
            var get = controller.Actions.Values.FirstOrDefault(a => a.Name.Equals("get", StringComparison.InvariantCultureIgnoreCase));
            if (get != null)
            {
                script.AppendLine($"    // get return type");
                string varStr = $"abp.schemas.{ module.Name.ToCamelCase()}.{ controller.Name.ToCamelCase()}.get";
                script.AppendLine($"    {varStr} = {varStr} || {{}};");
                var type = get.ReturnValue.Type;
                if (type != typeof(Task))
                {
                    if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(Task<>))
                    {
                        type = type.GetGenericArguments()[0]; // use this...
                    }
                    var schema = generator.GenerateAsync(type).GetAwaiter().GetResult();
                    var schemaData = schema.ToJson();
                    //schema.Title = action.ReturnValue.Type.Name;
                    script.Append($"    {varStr} =  ");
                    script.AppendLine(schemaData);
                }
            }
            // getall
            var getall = controller.Actions.Values.FirstOrDefault(a => a.Name.Equals("getall", StringComparison.InvariantCultureIgnoreCase));
            if (getall != null)
            {
                script.AppendLine($"    // getall parameters");
                string varStr = $"abp.schemas.{ module.Name.ToCamelCase()}.{ controller.Name.ToCamelCase()}.filter";
                //script.AppendLine($"    {varStr} = {varStr} || {{}};");


                if (getall.Parameters.Count == 1)
                {
                    script.Append($"    {varStr} = ");
                    //script.AppendLine("{");
                    foreach (var parameter in getall.Parameters)
                    {
                        var type = parameter.Type;
                        var schema = generator.GenerateAsync(type).GetAwaiter().GetResult();
                        if (parameter.BindingSourceId.IsIn(ParameterBindingSources.ModelBinding, ParameterBindingSources.Query))
                        {
                            schema.Title = parameter.Name;
                            schema.Default = parameter.DefaultValue;
                            //schema.re = parameter.IsOptional
                        }
                        var schemaData = schema.ToJson();
                        //script.Append($"    abp.schemas.{module.Name.ToCamelCase()}.{controller.Name.ToCamelCase()}.{action.Name.ToCamelCase()}.{parameter.Name.ToCamelCase()} =  ");
                        // script.Append($"    {parameter.Name.ToCamelCase()} :  ");
                        script.Append(schemaData).Append(";") ;
                        //script.AppendLine(",");
                    }
                    //script.AppendLine("    };");
                }
            }
            */
            foreach (var action in controller.Actions.Values)
            {
                AddActionScript(script, module, controller, action);
            }
        }

        private void AddActionScript(StringBuilder script, ModuleApiDescriptionModel module, ControllerApiDescriptionModel controller, ActionApiDescriptionModel action)
        {
            script.AppendLine($"// action '{action.Name.ToCamelCase()}'");
            script.AppendLine($"abp.schemas.{module.Name.ToCamelCase()}.{controller.Name.ToCamelCase()}.{action.Name.ToCamelCase()} = abp.schemas.{module.Name.ToCamelCase()}.{controller.Name.ToCamelCase()}.{action.Name.ToCamelCase()} || {{}};");
            var type = action.ReturnValue.Type;
            if (type != typeof(Task))
            {
                if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(Task<>))
                {
                    type = type.GetGenericArguments()[0]; // use this...
                }
                var schema = generator.GenerateAsync(type).GetAwaiter().GetResult();
                var schemaData = schema.ToJson();
                //schema.Title = action.ReturnValue.Type.Name;
                script.Append($"abp.schemas.{module.Name.ToCamelCase()}.{controller.Name.ToCamelCase()}.{action.Name.ToCamelCase()}.returnValue =  ");
                script.AppendLine(schemaData);
            }
            if (action.Parameters.Any())
            {
                script.Append($"abp.schemas.{module.Name.ToCamelCase()}.{controller.Name.ToCamelCase()}.{action.Name.ToCamelCase()}.parameters = ");
                script.AppendLine("{");
                foreach (var parameter in action.Parameters)
                {
                    type = parameter.Type;
                    var schema = generator.GenerateAsync(type).GetAwaiter().GetResult();
                    if (parameter.BindingSourceId.IsIn(ParameterBindingSources.ModelBinding, ParameterBindingSources.Query))
                    {
                        schema.Title = parameter.Name;
                        schema.Default = parameter.DefaultValue;
                        //schema.re = parameter.IsOptional
                    }
                    var schemaData = schema.ToJson();
                    script.Append($"    {parameter.Name.ToCamelCase()} :  ");
                    script.Append(schemaData);
                    script.AppendLine(",");
                }
                script.AppendLine("};");
            }
        }
    }
}